SELECT * FROM TB_CUSTOMERS CUST
JOIN TB_STATE STAT
ON STAT.Id = CUST.Id_STATE
JOIN TB_FINANCING FINA
ON FINA.Id_Customers = CUST.Id 
JOIN TB_FINANCING_INSTALLMENTS FIIN
ON FIIN.Id_Financing = FINA.Id
WHERE STAT.Description = 'SP'
AND 

SELECT TOP 4 * FROM TB_CUSTOMERS CUST
JOIN TB_FINANCING FINA
ON FINA.Id_Customers = CUST.Id 
JOIN TB_FINANCING_INSTALLMENTS FIIN
ON FIIN.Id_Financing = FINA.Id
WHERE FIIN.Expiration_Date > DATEADD(day, 5, CAST(GETDATE() AS DATE))
AND FIIN.Payment_Date IS NULL

SELECT * FROM TB_CUSTOMERS CUST
JOIN TB_FINANCING FINA
ON FINA.Id_Customers = CUST.Id 
JOIN TB_FINANCING_INSTALLMENTS FIIN
ON FIIN.Id_Financing = FINA.Id
WHERE FIIN.Expiration_Date > DATEADD(day, 10, CAST(GETDATE() AS DATE))
AND FINA.Total_Financing_Amount > 1000000